package uz.ilmnajot.elibrary.enums;

public enum SchoolName {

    SAMARKAND_PRESIDENTIAL_SCHOOL,
    TASHKENT_PRESIDENTIAL_SCHOOL,
    NAVOI_PRESIDENTIAL_SCHOOL,
    KHORAZIM_PRESIDENTIAL_SCHOOL,
    TERMIZ_PRESIDENTIAL_SCHOOL,
    DJIZZAKH_PRESIDENTIAL_SCHOOL,
    ANDIJAN_PRESIDENTIAL_SCHOOL,
    FARGANA_PRESIDENTIAL_SCHOOL,
    KARSHI_PRESIDENTIAL_SCHOOL,

}
